module.exports = {
  User: require("./User"),
  StudentProfile: require("./StudentProfile"),
  AdminProfile: require("./AdminProfile"),
  Exam: require("./Exam"),
  ExamQuestion: require("./ExamQuestion"),
  ExamAssignment: require("./ExamAssignment"),
  ExamSession: require("./ExamSession"),
  QuestionAttempt: require("./QuestionAttempt"),
  AntiCheatEvent: require("./AntiCheatEvent"),
  PracticeTopic: require("./PracticeTopic"),
  PracticeQuestion: require("./PracticeQuestion"),
  PracticeAttempt: require("./PracticeAttempt"),
  StudentTopicStat: require("./StudentTopicStat"),
  Badge: require("./Badge"),
  StudentBadge: require("./StudentBadge"),
  LeaderboardSnapshot: require("./LeaderboardSnapshot"),
  Notice: require("./Notice"),
  MonitoringSession: require("./MonitoringSession"),
  PyqSet: require("./PyqSet"),
};
